# Generated by Django 5.2.8 on 2025-11-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='datasets/')),
                ('row_count', models.IntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
